### ISSUE TITLE
Carthage build broken, Willow dependency missing

### ISSUE THREAD

**Issue by binloan** [Azure/Azure.iOS#100]
## Bug Information
It is not possible to build Azure.iOS via Carthage in its current configuration. The nested dependency to Willow produces an error at build time.

### Steps to Reproduce
Add the framework path to your Cartfile and run `carthage update`. The build will fail with the above reason.

### Expected Behavior
The nested Willow dependency is added via a nested Cartfile. 
EDIT: Actually is part of the projects, but seems to not work.

### Actual Behavior
Carthage fails, because it does not know about the dependency.

**Comment by colbylwilliams** [comment]
@binloan I just pushed a new release, should resolve you're issue.  Try running `carthage update` again and please let me know if the issue is resolved.

**Comment by kingbin** [comment]
I'm still getting this error using v 0.2 and master. Was there something lost in a merge?

**Comment by NateRickard** [comment]
@ftchirou can you review this?

**Comment by jakobmygind** [comment]
Any news on this?

**Comment by ftchirou** [comment]
Are you experiencing the issue? @jakobmygind

**Comment by jakobmygind** [comment]
@ftchirou Yes, I am. Do you need additional info?
