### ISSUE TITLE
partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#108]
## Bug Information
Received this error after trying to retrieve all collections in the database

```
BadRequest | The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.
ActivityId: d6f2ee8b-0863-4fd6-b818-c6795c44bc04
Request URI: /apps/4270906a-2001-4446-8042-4bebcb78d23a/services/b46badbc-b14d-4a04-88e0-cb04d5146585/partitions/b134861e-6fa8-474a-a9a6-960ed909e0db/replicas/131934514209902361p/
RequestStats: 
RequestStartTime: 2019-02-01T10:15:55.9803291Z, Number of regions attempted: 1
```

Note that "Storage Capacity" on the collection is ```Unlimited```

Partition key was set to "id/type"

### Steps to Reproduce
    AzureData.get (collectionsIn: "sogodb") { r in
        // collections = r.resource?.items
        print(r.resource?.items)
    }

### Screenshots
![image](https://user-images.githubusercontent.com/19580787/52117458-e3645080-2667-11e9-810d-2421572479b6.png)

**Comment by julianparismorgan** [comment]
I'm having the same issue with creating documents.

 ```
var document = CustomDocument()

        document.testDate   = Date(timeIntervalSince1970: 1510865595)
        document.testNumber = 1234
        document.anchorId = "1234567890"
        document.regionCode = "US"

        AzureData.create (document, inCollection: "Anchors", inDatabase: "Items") { r in
            debugPrint(r.result)
            if let document = r.resource {
                let test = document
            } else if let error = r.error {
                debugPrint(error.localizedDescription)
            }
        }
```

❌ FAILURE: ❌ badRequest ❌
BadRequest | The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.

ActivityId: 8f4e02df-9f3b-4817-ac37-282d50f441e1

Have regionCode set as the partition key: 
![image](https://user-images.githubusercontent.com/1396242/52182961-1a497c00-27b8-11e9-90c6-a440c687ac92.png)

**Comment by SogoGolf** [comment]
@NateRickard are these issues same/related? https://github.com/Azure/Azure.Android/issues/75

**Comment by ftchirou** [comment]
Yes. They are related @SogoGolf.

**Comment by NateRickard** [comment]
Closing as PR #114 should have fixed this behavior
