### ISSUE TITLE
Cache Error [_cache]: The file “8-QFAP6IEpwfAAAAAAAAAA==” doesn’t exist

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#109]
## Bug Information
seeing a lot of cache errors after retrieving documents (with ```offlineDataEnabled = true```). These cache errors appear each time the same query is called.

### Steps to Reproduce
macOS Mojave 10.14.2
XCode Version 10.1 (10B61)

Create a new iOS app project in Xcode.

**Step 1**

    AzureData.configure(withPlistNamed: "Info.plist", withPermissionMode: PermissionMode.all)
    AzureData.offlineDataEnabled = true

    //now get some documents
    AzureData.get (documentsAs: GolferDocument.self, inCollection: "<your collection>", inDatabase: "<yourdb>") { r in
    guard let items = r.resource?.items else {
        print("no items returned")
        return
    }
    for item in items {
        print("\(item.firstName) \(item.lastName)")
    }

The data from the query above IS returned correctly.

However - take a look at the logs. There's also a list (in this example) of about 20+ cache error lines as noted below.

**Step 2**
Now take the app offline (but DONT restart the Xcode project)
Go back to your app and run the same query above (I had it hooked up to a button tap event)

NO cache errors appear.

**Step 3**
Bring the app back online.
Re-run the same query.

NO cache errors appear.

### Expected Behavior
no cache errors when calling the Azure.iOS api for the first time

### Actual Behavior
    2019-02-03 12:31:23.665135+1100 azuretest[2636:42806] [azure] ❌ Cache Error [_cache]: The    file “8-QFAP6IEpwfAAAAAAAAAA==” doesn’t exist.
    2019-02-03 12:31:23.666146+1100 azuretest[2636:42800] [azure] ❌ Cache Error [_cache]: The file “8-QFAP6IEpwdAAAAAAAAAA==” doesn’t exist.

**Comment by colbylwilliams** [comment]
@SogoGolf can you confirm this is still happening in [v0.4.0](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.0) (latest cocoapod released)?

**Comment by colbylwilliams** [comment]
It seems this only happens on the simulator.  Closing issue, if this is causing someone issues on device, please open an new issue and reference this issue.
