### ISSUE TITLE
AzureData.replace throwing partition key error

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#112]
## Bug Information
Honestly i don't know if I am calling this part of the api correctly, but the behaviour I got today was when invoking AzureData.replace() the document was _deleted_ from the collection.

### Steps to Reproduce

Just to note ```updateId``` below is an existing documents id

Here's the code:
```
  AzureData.get (documentWithId: updateId, as: GolferDocument.self, inCollection: "sogocollection",      
       inDatabase: "sogodb") { r in
	let doc = r.resource

       //just change the first name property
	doc?.firstName = "new fname \(timestamp)"

        //now replace that document
	AzureData.replace (doc!, inCollection: "sogocollection", inDatabase: "sogodb") { r in
		print(r.resource)
		print(r.error)
	}
    }
```
### Expected Behavior
document is updated

### Actual Behavior
document was deleted

**Comment by colbylwilliams** [comment]
@SogoGolf can you confirm this is still happening in [v0.4.0](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.0) (latest cocoapod released)?

**Comment by SogoGolf** [comment]
hey @colbylwilliams ill look to test 0.4.0 tomorrow and will post back here

**Comment by SogoGolf** [comment]
```.replace(...``` is no longer deleting the document. however it fails now with a "partition key header" error. so that should be fixed.

also just to note, ```.createOrReplace``` does work (replaces the doc correctly and does not throw a partition key error)
