### ISSUE TITLE
Access query data whilst offline

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#113]
query ❌ FAILURE is returned if a query is called whilst the device is offline

is this expected behaviour based on the Preview Release API's ? we cant really use Azure.iOS offline without the ability to query the locally sync'd data, or minimally, re-access data previously returned from a query (when online)

**Comment by ftchirou** [comment]
Hey @SogoGolf! Querying is not yet supported while offline. I do agree that we should probably at least return data resulting from the latest queries performed while online.

**Comment by ajonno** [comment]
Thanks @ftchirou. Could you give me any kind of eta for adding this?

**Comment by SogoGolf** [comment]
Thanks @ftchirou. Could you give me any kind of eta for adding this?

**Comment by NateRickard** [comment]
Closing - support for this should have been added in PR #115
