### ISSUE TITLE
orderBy desc returning typeMismatch error

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#117]
hi @ftchirou, info as follows:

**Query**
`let query = Query.select()
.from("collection")
.where("type", is: "transaction")
.and("golferEmail", is: "xxxx@yyyy.com")
.orderBy("transactionDate", descending: true)`

```descending:true``` seems to be causing the issue

**Result**
nil (incorrect; should return data)

*Note: this exact same query, against same data set in CosmosDB, returns data correctly on Azure.Android (0.2.+)*

![image](https://user-images.githubusercontent.com/19580787/55199656-dfd7ea80-520e-11e9-8595-624af6eecadb.png)

**Model class**
```
class TransactionDocument: Document {
	static let partitionKey: String = "/type"

	var old_id: Int? 
	var golferId: String? 
	var golferFirstName:  String?
	var golferLastName:  String?
	var golferEmail: String? 
	var transactionDate: String?
	var transactionValue: Int?
	var availableTokens: Int?

	public override init () { super.init() }
	public override init (_ id: String) { super.init(id) }

	public required init(from decoder: Decoder) throws {
		try super.init(from: decoder)
		
		let container = try decoder.container(keyedBy: CodingKeys.self)
		
		old_id = try container.decode(Int.self,   forKey: .old_id)
		golferId = try container.decode(String.self,   forKey: .golferId)
		golferFirstName = try container.decode(String.self,   forKey: .golferFirstName)
		golferLastName = try container.decode(String.self,   forKey: .golferLastName)
		golferEmail = try container.decode(String.self,   forKey: .golferEmail)
		transactionDate = try container.decode(String.self,   forKey: .transactionDate)
		transactionValue = try container.decode(Int.self,   forKey: .transactionValue)
		availableTokens = try container.decode(Int.self,   forKey: .availableTokens)
	}

	public override func encode(to encoder: Encoder) throws {
		try super.encode(to: encoder)
		
		var container = encoder.container(keyedBy: CodingKeys.self)
		
		try container.encode(old_id,   forKey: .old_id)
		try container.encode(golferId,   forKey: .golferId)
		try container.encode(golferFirstName,   forKey: .golferFirstName)
		try container.encode(golferLastName,   forKey: .golferLastName)
		try container.encode(golferEmail,   forKey: .golferEmail)
		try container.encode(transactionDate,   forKey: .transactionDate)
		try container.encode(transactionValue,   forKey: .transactionValue)
		try container.encode(availableTokens,   forKey: .availableTokens)
	}
	
	private enum CodingKeys: String, CodingKey {
		case old_id
		case golferId
		case golferFirstName
		case golferLastName
		case golferEmail
		case transactionDate
		case transactionValue
		case availableTokens
	}
}
```

**Comment by ftchirou** [comment]
Hi @SogoGolf! There is a fix already merged for this bug in `master` and your issue will be solved in the next release of the SDK 🙂.

Furthermore, the implementation of your `TransactionDocument` should be greatly simplified in the next release. You wouldn't need the overridden `init`s and you would be able to let the compiler automatically synthetize the `Codable` conformance. Your class could look something like below.

```swift
class TransactionDocument: Document {
    static let partitionKey = \.type

    let old_id: Int
    let golferId: String
    let golferFirstName:  String
    let golferLastName:  String
    let golferEmail: String
    let transactionDate: String
    let transactionValue: Int
    let availableTokens: Int
    let type: String

    public init(/*...*/) {
        // ...
    }
}
```

**Comment by SogoGolf** [comment]
brilliant thanks @ftchirou!

**Comment by SogoGolf** [comment]
hi @ftchirou i installed 0.3.0 today but still saw this same error unf. 

for this example using 0.3.0, i updated the Transaction model object and had no issues.

also, doing an orderBy without "descending: true" worked fine.

let me know if you need any additional info to help resolve. much appreciated.

**Comment by ftchirou** [comment]
Hi @SogoGolf! Could you unroll the field `codingPath` in `baseError` and share the contents here?  Could you also share what `debugDescription` contains?

**Comment by SogoGolf** [comment]
hi @ftchirou here's the expanded error tree (as far as it would go):

![image](https://user-images.githubusercontent.com/19580787/56100797-73741f80-5f60-11e9-884d-f426cbeb741d.png)

**Comment by SogoGolf** [comment]
alrighty, @ftchirou super sleuth helped find the problem which actually exists directly in the data, hence the type mismatch. sorry about that! ill look into how that occurred and close the ticket. thanks again @ftchirou !
