### ISSUE TITLE
Can't create any document that needs a partition key - sample code is broken

### ISSUE THREAD

**Issue by ayrtonsoftware** [Azure/Azure.iOS#119]
*Only submit issues here for the iOS SDKs -- Issues in the deployment template and functions should be submit in aka.ms/mobile*

If you are creating an issue for a **BUG** please fill out the applicable information below. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and link to it here.

**Comment by ayrtonsoftware** [comment]
`final class CosmosObject: Document {
    static var partitionKey: KeyPath<CosmosObject, String>?
    var id: String
    var guid: String = ""
    var category: String = ""
    var substrings: [String] = []
    var partitionKey: String = ""

    init(category: String) {
        self.partitionKey = "Me"
        self.guid = UUID().uuidString
        self.id = self.guid
        self.category = category
        self.substrings = []
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try! container.encode(substrings, forKey: .substrings)
        try! container.encode(id, forKey: .id)
        try! container.encode(guid, forKey: .guid)
        try! container.encode(category, forKey: .category)
        try! container.encode(partitionKey, forKey: .partitionKey)
    }
    
    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        substrings = try! container.decode([String].self, forKey: .substrings)
        id = try! container.decode(String.self, forKey: .id)
        category = try! container.decode(String.self, forKey: .category)
        partitionKey = try! container.decode(String.self, forKey: .partitionKey)
        guid = try! container.decode(String.self, forKey: .guid)
    }
    
    private enum CodingKeys: String, CodingKey {
        case id
        case substrings
        case category
        case partitionKey
        case guid
    }
}`

**Comment by ayrtonsoftware** [comment]
if create {
                                    var obj = CosmosObject(category: "Car")
                                    obj.substrings.append("New\(Date())")
                                    obj.substrings.append("CosmosDB Test")
                                    AzureData.create(obj, in: collection, callback: { (response: Response<CosmosObject>) in
                                        if let f = response.resource {
                                            print(f)
                                        } else {
                                            print(response)
                                            if let data = response.data {
                                                var what = String(data: data, encoding: .utf8)
                                                print(what)
                                            }
                                        }
                                    })
                                }

**Comment by ayrtonsoftware** [comment]
> final class CosmosObject: Document {
>     static var partitionKey: KeyPath<CosmosObject, String>?
>     var id: String
>     var guid: String = ""
>     var category: String = ""
>     var substrings: [String] = []
>     var partitionKey: String = ""
> 
>     init(category: String) {
>         self.partitionKey = "Me"
>         self.guid = UUID().uuidString
>         self.id = self.guid
>         self.category = category
>         self.substrings = []
>     }
>     
>     func encode(to encoder: Encoder) throws {
>         var container = encoder.container(keyedBy: CodingKeys.self)
>         try! container.encode(substrings, forKey: .substrings)
>         try! container.encode(id, forKey: .id)
>         try! container.encode(guid, forKey: .guid)
>         try! container.encode(category, forKey: .category)
>         try! container.encode(partitionKey, forKey: .partitionKey)
>     }
>     
>     required init(from decoder: Decoder) throws {
>         let container = try decoder.container(keyedBy: CodingKeys.self)
>         substrings = try! container.decode([String].self, forKey: .substrings)
>         id = try! container.decode(String.self, forKey: .id)
>         category = try! container.decode(String.self, forKey: .category)
>         partitionKey = try! container.decode(String.self, forKey: .partitionKey)
>         guid = try! container.decode(String.self, forKey: .guid)
>     }
>     
>     private enum CodingKeys: String, CodingKey {
>         case id
>         case substrings
>         case category
>         case partitionKey
>         case guid
>     }
> }
> 
> 
> if create {
>                                     var obj = CosmosObject(category: "Car")
>                                     obj.substrings.append("New\(Date())")
>                                     obj.substrings.append("CosmosDB Test")
>                                     AzureData.create(obj, in: collection, callback: { (response: Response<CosmosObject>) in
>                                         if let f = response.resource {
>                                             print(f)
>                                         } else {
>                                             print(response)
>                                             if let data = response.data {
>                                                 var what = String(data: data, encoding: .utf8)
>                                                 print(what)
>                                             }
>                                         }
>                                     })
>                                 }

**Comment by ayrtonsoftware** [comment]
> final class CosmosObject: Document {
    static var partitionKey: KeyPath<CosmosObject, String>?
    var id: String
    var guid: String = ""
    var category: String = ""
    var substrings: [String] = []
    var partitionKey: String = ""

    init(category: String) {
        self.partitionKey = "Me"
        self.guid = UUID().uuidString
        self.id = self.guid
        self.category = category
        self.substrings = []
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try! container.encode(substrings, forKey: .substrings)
        try! container.encode(id, forKey: .id)
        try! container.encode(guid, forKey: .guid)
        try! container.encode(category, forKey: .category)
        try! container.encode(partitionKey, forKey: .partitionKey)
    }
    
    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        substrings = try! container.decode([String].self, forKey: .substrings)
        id = try! container.decode(String.self, forKey: .id)
        category = try! container.decode(String.self, forKey: .category)
        partitionKey = try! container.decode(String.self, forKey: .partitionKey)
        guid = try! container.decode(String.self, forKey: .guid)
    }
    
    private enum CodingKeys: String, CodingKey {
        case id
        case substrings
        case category
        case partitionKey
        case guid
    }
}

**Comment by ayrtonsoftware** [comment]
```
final class CosmosObject: Document {
    static var partitionKey: KeyPath<CosmosObject, String>?
    var id: String
    var guid: String = ""
    var category: String = ""
    var substrings: [String] = []
    var partitionKey: String = ""

    init(category: String) {
        self.partitionKey = "Me"
        self.guid = UUID().uuidString
        self.id = self.guid
        self.category = category
        self.substrings = []
    }
    
    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try! container.encode(substrings, forKey: .substrings)
        try! container.encode(id, forKey: .id)
        try! container.encode(guid, forKey: .guid)
        try! container.encode(category, forKey: .category)
        try! container.encode(partitionKey, forKey: .partitionKey)
    }
    
    required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        substrings = try! container.decode([String].self, forKey: .substrings)
        id = try! container.decode(String.self, forKey: .id)
        category = try! container.decode(String.self, forKey: .category)
        partitionKey = try! container.decode(String.self, forKey: .partitionKey)
        guid = try! container.decode(String.self, forKey: .guid)
    }
    
    private enum CodingKeys: String, CodingKey {
        case id
        case substrings
        case category
        case partitionKey
        case guid
    }
}


 if create {
                                    var obj = CosmosObject(category: "Car")
                                    obj.substrings.append("New\(Date())")
                                    obj.substrings.append("CosmosDB Test")
                                    AzureData.create(obj, in: collection, callback: { (response: Response<CosmosObject>) in
                                        if let f = response.resource {
                                            print(f)
                                        } else {
                                            print(response)
                                            if let data = response.data {
                                                var what = String(data: data, encoding: .utf8)
                                                print(what)
                                            }
                                        }
                                    })
                                }
```

**Comment by ftchirou** [comment]
Hey @ayrtonsoftware! Thanks for reporting the issue. Can you share the exact error you're receiving so I can assist you to solve this issue?

Also let me know the error you have if you update your class definition to the one below?

```swift
final class CosmosObject: Document {
    static let partitionKey = \.partitionKey

    var id: String
    var guid: String = ""
    var category: String = ""
    var substrings: [String] = []
    var partitionKey: String = ""

    init(category: String) {
        self.partitionKey = "Me"
        self.guid = UUID().uuidString
        self.id = self.guid
        self.category = category
        self.substrings = []
    }
}
```

**Comment by ayrtonsoftware** [comment]
I am using v0.3.0 - and Xcode Version 10.2 (10E125) I tried this and get a compile error :

static let partitionKey = \.partitionKey
                                        ^

Type of expression is ambiguous without more context.

**Comment by ftchirou** [comment]
Thanks @ayrtonsoftware! Explicitly adding the type of `partitionKey` should solve that compile error.

```swift
static let partitionKey: PartitionKey? = \.partitionKey
```

Let me know if that works.

**Comment by ayrtonsoftware** [comment]
Thanks for quick response. That did it... and the create seemed to work. Now I am going to verify on the portal...... cheers
