### ISSUE TITLE
partition key error calling stored proc (v0.3.0)

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#121]
tried to call a test stored proc and saw the following error. is this because the stored proc API methods need a partition key param added?

```BadRequest | PartitionKey extracted from document doesn't match the one specified in the header```

**API call**
```
AzureData.execute(storedProcedureWithId: "purchaseTokens", usingParameters: [], inCollection: "collection", inDatabase: "db") {
	result in
	print(result)
}

```

**Stored Proc** (setup in portal)
```
function purchaseTokens() {

    var collection = getContext().getCollection();

    var isAccepted = collection.queryDocuments(
        collection.getSelfLink(),
        `SELECT f.id FROM f WHERE f.type = 'entity'`,

        function (err, data, options) {
            if (err) throw err;

            if (!data || !data.length) {
                var response = getContext().getResponse();
                response.setBody([{hmm: "nothin there"}]);
            }
            else {
                var response = getContext().getResponse();
                response.setBody({sku: "sku"});
            }
        });

    if (!isAccepted) throw new Error('The query was not accepted.');
}
```

**Comment by NateRickard** [comment]
@colbylwilliams @ftchirou refer to https://github.com/Azure/Azure.Android/pull/97.  I found that the partition key value was required only when the stored proc was doing something like executing a query.  See the `executeStoredProcedureWithQuery` test in Android for an example.

**Comment by ftchirou** [comment]
Noted. Thanks @NateRickard.

**Comment by SogoGolf** [comment]
@ftchirou @colbylwilliams i tried 0.4.0 today to test calling a stored proc but still saw partition key errors. does the function signature require the partition key ?

**Comment by SogoGolf** [comment]
tested and works perfectly thanks! one thing i did notice was the old function signatures (no partition key) showing up in Xcode
