### ISSUE TITLE
AzureCore.Result conflicts with Swift.Result

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#127]
### Environment

- iOS version: 12.3
- Xcode version: 10
- Azure.iOS SDK version:  0.4.0

### Bug Summary
hi all, getting a collision with Swift's “Result”.  

error is:
```Generic type ‘Result’ specialized with too many type parameters (got 2, but expected 1)```

### Code snippet
example method signature:
```swift
func createUser(email: String, password: String, completion: @escaping (Result<Bool, Error>) -> Void) {
    ….
}
```

### Expected Behavior
be able to use Swift's Result type without collision with Azure.iOS APIs

**Comment by SogoGolf** [comment]
@colbylwilliams i tried to test this today but still saw the build error. i thought maybe i needed to bump pod version to 0.4.1 but that didn't resolve. am wondering if I'm missing something ?

**Comment by colbylwilliams** [comment]
@SogoGolf v0.4.1 was just release.  Please try again.

**Comment by SogoGolf** [comment]
0.4.1 resolved the build error which is great.

however i noticed a new build error for a different method ```AzureData.delete``` that I also have in the test project.

![image](https://user-images.githubusercontent.com/19580787/58517537-0f937680-81ef-11e9-9924-57f7a04c97bd.png)

I can easily unpack/switch now on the Result<Data, Error> but am wondering if this related issue is known ? If so the docs should probably be updated too since ```r.isSuccess``` is no longer available: https://github.com/Azure/Azure.iOS/tree/master/AzureData#delete-2
