### ISSUE TITLE
query's not handling strings with single quote

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#129]
### Environment

- iOS version:
- Xcode version: Version 10.2.1 (10E1001)
- Azure.iOS SDK: 0.3.0
- CocoaPods or Carthage: cocoapods

### Bug Summary
Queries returning 0 results on WHERE clause when the string to match on (on server/CosmosDB) contains a single quote

Note that this is with 0.3.0 of API. I'll double check this is still occurring on latest version 0.4.0 but till then will leave this ticket open

### Steps to Reproduce
add a doc that has a "name" (say) field with a value of:  
```
"name": "St Michael's Golf Club",
....
```

### Code snippet

```swift
let name = "St Michael's Golf Club"
let query = Query.select()
			.from("acollection")
			.where("type", is: "something")
			.and("name", is: name)
```

### Expected Behavior
1 doc returned

### Actual Behavior
0 docs returned

**Comment by colbylwilliams** [comment]
@SogoGolf this should be fixed [v0.4.2](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.2)+.  Can you confirm before I close this issue?
