### ISSUE TITLE
Queries allow boolean values

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#130]
### Feature Summary
would it be possible to have a ```.and(String, Bool)``` **query** function signature. tried it today and wasn’t available, really need this.

### Recommended Solution
eg. ```.and("myBoolProperty", true)```

**Comment by SogoGolf** [comment]
Hey @colbylwilliams thanks for adding this in. Is it ready to go if I update podfile to 0.4.2?

**Comment by colbylwilliams** [comment]
@SogoGolf almost.  I partially added it to [v0.4.2](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.2), but it only supports querying for boolean properties with a value of `true`.  I'm publishing [v0.4.3](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.3) now that will support querying for both `true` and `false`.  [v0.4.3](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.3) should be available within the hour.

**Comment by colbylwilliams** [comment]
@SogoGolf [v0.4.3](https://github.com/Azure/Azure.iOS/releases/tag/v0.4.3) adds functionality for querying boolean properties.  Please confirm this works as expected.  Feel free to reopen this issue if you have trouble.

**Comment by ajaamsco** [comment]
used updated api today and all looks good. many thanks @colbylwilliams !
