### ISSUE TITLE
add query support for ARRAY_LENGTH

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.iOS#131]
### Feature Summary

support for queries that use the ARRAY_LENGTH qualifier, eg. from the SQL API JS syntax:

```SELECT count(c.id) as rounds18Count FROM c where c.type = "round" and ARRAY_LENGTH(c.holeScores) = 18 and c.isDeleted = false```

provide that same capability in the Azure.iOS query API

**Comment by colbylwilliams** [comment]
@SogoGolf I'm just published a new version (v0.4.4) that contains a work-around, until I can implement more of the Query DSL to support more SQL functions with chained function calls (like `where`, `and`, etc.).

The update (v0.4.4) contains a new static constructor for `Query` that takes a raw SQL query string:

```swift
public static func createFrom(queryString: String) -> Query
```

The query in your comment would looks something like this:

```swift
let query = Query.createFrom(queryString: #"SELECT count(c.id) as rounds18Count FROM c WHERE c.type = "round" AND ARRAY_LENGTH(c.holeScores) = 18 AND c.isDeleted = false"#)
```

However, I'm not sure you want to use `as rouds18Count` in the query string you provide.  You're going to get back the type that you pass into the `AzureData.query` as you normally would.  So you may not be able to retrieve just the count, but you can experiment.

Something like this should definitely work though:

```swift
let query = Query.createFrom(queryString: #"SELECT c.id FROM c WHERE c.type = "round" AND ARRAY_LENGTH(c.holeScores) = 18 AND c.isDeleted = false"#)

AzureData.query(documentPropertiesIn: myCollection, with: query, andPartitionKey: "myKey") { response in
    let roundsCount = response.resource.count
}
```

Hope this helps.

**Comment by SogoGolf** [comment]
Legend many thanks @Colby Williams . ill test this out and let you know

**Comment by colbylwilliams** [comment]
Closing this issue.  Feel free to reopen if the fix mentioned above didn't resolve the issue.
