### ISSUE TITLE
Add additional metadata to Response object

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.iOS#15]
Add [metadata](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.resourceresponse-1?view=azure-dotnet) to response object

**Comment by colbylwilliams** [comment]
Resource: [Common Azure Cosmos DB REST response headers](https://docs.microsoft.com/en-us/rest/api/documentdb/common-documentdb-rest-response-headers)

**Comment by ftchirou** [comment]
For clarification, does this task consist in adding the response headers as properties of the `Response` object?

e.g.

```swift
extension Response {
    var sessionToken: String {
        // return the value of the `x-ms-session-token` header
    }
}
```

@colbylwilliams

**Comment by colbylwilliams** [comment]
Let's create a single metadata object that holds all the header values associated with cosmos specific things like request units.  it should have an `init` that takes a `HTTPURLResponse` (that's already a property on the `Response` object) an populates it's own properties using the `HTTPURLResponse`'s headers.  Then make a single `lazy` property on the `Response` object so we're not spending time parsing the headers unless the user actually accesses the object.
