### ISSUE TITLE
Implement support for Pagination of query results and feeds

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.iOS#21]
[Pagination of query results](https://docs.microsoft.com/en-us/rest/api/documentdb/querying-documentdb-resources-using-the-rest-api#pagination-of-query-results)

**Comment by ftchirou** [comment]
Hi @colbylwilliams! I wanted to share some thoughts I have about pagination. Let me know what you think.

On a high level, users should be able to query resources like the following (assuming we're querying `Document`s in the example).

```swift
AzureData.query(50, documentsIn: collectionId, inDatabase: databaseId, with: query) { page in
}
```
The prototype of the above function would be

```swift
func query(
    _ documentsPerPage: Int? = nil,
    documentsIn collectionId: String,
    inDatabase databaseId: String, 
    with query: Query, 
    callback: (Response<Page<T>>) -> ()
)
```

`page` would be an object of type `Page` that encapsulates a `Resources<T>` object and has the following public properties:

- `items: [T]` the actual list of resources
- `itemsCount: Int` the number of items in this page
- `isLast: Bool` whether this is the last page or not.

`Page` would also contain a function to fetch the next page of items.

```swift
page.next { nextPage in 
}
```

**Comment by ftchirou** [comment]
Thoughts and/or feedback on the above? @colbylwilliams  @NateRickard

**Comment by colbylwilliams** [comment]
1. Could we put the page limit on the [`Query`](https://github.com/Azure/Azure.iOS/blob/master/AzureData/Source/Query.swift) object?  
2. We need to add the type for the document-specific similar to the [list overrides](https://github.com/Azure/Azure.iOS/tree/master/AzureData#list-2)
3. The list calls also have the option to page, so let's add the functionality directly to the `Resources<T>` object

**Comment by ftchirou** [comment]
Adding the page limit to the `Query` object would work great for `query` calls. How about the `list` calls? Those don't take a `Query` in parameter.

**Comment by colbylwilliams** [comment]
true... maybe an optional `max` param?  I want to make sure either way, that we default (to 100) so its not required to pass in a value

**Comment by colbylwilliams** [comment]
@ftchirou No, you're right, there should be consistency... just add an optional param to both the `list` and `query` functions and don't add it to the `Query` object... So:
- [ ] Instead of defaulting the value to 100, make it nullable and default to `nil` and just don't add the header if the value is `nil` (just incase Cosmos changes the default to something other than 100, we won't have to make a change to the SDK)
- [ ] Validate if the value isn't nil, it is between 1 and 1000 and return an error as appropriate

**Comment by ftchirou** [comment]
Gotcha @colbylwilliams ! So from a user perspective, are the following APIs okay?

### query

```swift
// Specifying the number of items per page
AzureData.query(24, documentsAs: Document.self, inCollection: collectionId, inDatabase: databaseId) { r in
}

// Leaving the number of items per page to the default set by CosmosDB.
AzureData.query(documentsAs: Document.self, inCollection: collectionId, inDatabase: databaseId) { r in
}
```

### list

```swift
// Specifying the number of items per page
AzureData.get(30, collectionsIn: databaseId) { r in 
}

// Leaving the number of items per page to the default set by CosmosDB.
AzureData.get(collectionsIn: databaseId) { r in 
}
```

### paginating

```swift
/// Assuming `resources` is an object of type `Resources<T>`.
resources.more { r in
    // next set of items = r.resources
}
```

**Comment by colbylwilliams** [comment]
@ftchirou The max number of items param should be the last param in the func (or the one right before the callback), so:

```swift
AzureData.query(documentsAs: Document.self, inCollection: collection, with: query, itemsPerPage: 50) { r in
}
```

for paginating, let's use `next` instead of `more`, but I'm not sure you'll have the metadata you'll need on the `Resources<T>` object itself to create the next request... you'll have to prototype and see.  We should also add a `hasMoreResults` bool on the `Resources<T>`, so we can perform while loops:

```swift
while resources.hasMoreResults {
    resources.next {

    }
}
```

**Comment by ftchirou** [comment]
- Noted about having the `itemsPerPage` parameter before the `callback`. It just sounded nice when reading the code with the parameter at the beginning (`get 100 documents in ...`) 🙃.
- Yes! Agree about `hasMoreResults`. In my first comment, I named it `isLast` but `hasMoreResults` sounds better. Or just `hasMore`?
- And yes. I'll have to add some `internal` properties to `Resources<T>` to allow it to fetch the next set of results.

**Comment by ftchirou** [comment]
Can we close this issue since we have a basic set of APIs defined? @colbylwilliams. We can continue with the discussion and feedback on #22 and on the PR comments section.

**Comment by colbylwilliams** [comment]
@ftchirou no point in splitting it out... Are you good with closing issue #22 and renaming this one from "Design.." to "Implement..."?

**Comment by ftchirou** [comment]
Yup. Works for me.

**Comment by ftchirou** [comment]
And done ✅.

**Comment by ftchirou** [comment]
Hey @colbylwilliams! I added the pagination support (`hasMore` and `next`) to the `Resources<T>` object as discussed here. I was wondering if it won't be more appropriate on the `Response<T>` object because 

1. it seems more logical than on `Resources<T>`
2. everything necessary to make the next request is already available in the `Response<T>` object
3. it will require minimal code change (just an extension function `next` and a computed property `hasMoreResults` on `Response<T>`)

What do you think?

**Comment by colbylwilliams** [comment]
Yeah, I agree.  See if you can constrain the extension to only Response<T> where T == Resources.

**Comment by ftchirou** [comment]
Yes. That's where it becomes tricky.
