### ISSUE TITLE
AzureCore Library Dependencies: Secure Storage

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.iOS#3]
Determine best **MIT Licensed** OSS library to provide functionality exposed in AzureCore.

List suggested libraries in comments for review and final decision.

**Comment by colbylwilliams** [comment]
Currently between _(leaning more towards KeychainAccess)_:

**[Locksmith](https://github.com/matthewpalmer/Locksmith)**
- 3679+ Starts
- 368+ Forks

**[KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess)**
- 2496+ Starts
- 204+ Forks

**Comment by colbylwilliams** [comment]
@ftchirou do you have a preference or feedback on using one of these libraries over the other?

**Comment by ftchirou** [comment]
I have experience with KeychainAccess so my preference will lean towards it @colbylwilliams. Let me have a look at Locksmith.

**Comment by colbylwilliams** [comment]
@ftchirou I was leaning towards KeychainAccess anyway, so don't worry about looking into Locksmith, let's just move forward with KeychainAccess.

**Comment by ftchirou** [comment]
Sounds good.
