### ISSUE TITLE
Data Persistence (offline read)

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.iOS#30]
_For the initial phase (and the scope of this issue), only **read** operations (`get`, `list`) will be supported while device is offline, write operations (`create`, `delete`) will be implemented in the next phase._

**Resources are to be cached/written to disk locally as folders/files rather than using a structured database implementation such as SQLite.  The folder/file structure will match the path the resources `selfLink` value - the path constructed using a Resource's and its associated Parent's system generated resource IDs (`_rid`).**

### Example
A Document resource in the database account `https://databaseaccount.database.com` located at the following path _(`selfLink`)_:
```
dbs/1KtjAA==/colls/1KtjAImkcgw=/docs/1KtjAImkcgwBAAAAAAAAAA==/
```

Would be represented in the file system like this (square brackets indicate folders):
```
[databaseaccount.database.com]
└──[dbs]
    └──[1KtjAA==]
        ├──1KtjAA==.json
        └──[colls]
            └──[1KtjAImkcgw=]
                ├──1KtjAImkcgw=.json
                └──[docs]
                    └──[1KtjAImkcgwBAAAAAAAAAA==]
                        ├──1KtjAImkcgwBAAAAAAAAAA==.json
                        └──[attachments]
                            └──...
```

### Initial Requirements
- [x] Add user-facing API to enable/disable offline persistence (enabled by default)
- [x] Data must be **successfully** written remotely before caching locally _(indicated by a response status code of `201 Created`)_
- [x] Data should _only_ be returned from local cache if the device is offline, otherwise data is always retrieved from remote database
- [x] The Response object's [`fromCache`](28) property should be set to `true` when returning data from local cache (device offline)
- [x] Expose a simple user-facing API to purge *entire* data cache
- [x] `DELETE`ing a resource remotely should delete the cached version (if the delete was successful indicated by a response status code of `204 No Content`)
- [x] If an attempt to `GET` a resource from the remote database returns `404 Not Found` (indicating the resource has been deleted/no longer exists in the remote database), confirm that resource does **not** exist locally, and if it does, delete it
- [x] When deleting a resource locally, also delete the associated record from the [`id` <-> `_rid` relationship store](26)
- [x] Expose a user-facing API (likely a `protocol` with `encrypt` and `decrypt` functions) to allow user to implement custom data encryption 
- [x] ~~If user attempts a write operation (`create`, `delete`) throw a (useful) error indicating this functionality will be supported in future releases.~~ See #73 for offline write

**Comment by ftchirou** [comment]
In addition to all the above which is great, I think the online and offline capabilities of the framework should have the same public interface. Right now, we have an online client named `DocumentClient` and a `ResourceCache` for local persistence. 

1. What if we made `DocumentClient` into a protocol

```swift
protocol DocumentClient {

    // MARK: - Databases

    func create (databaseWithId databaseId: String, callback: @escaping (Response<Database>) -> ())
    func databases (maxPerPage: Int? = nil, callback: @escaping (Response<Resources<Database>>) -> ())

    // ...

    // MARK: - Collections

    func create (collectionWithId collectionId: String, inDatabase databaseId: String, callback: @escaping (Response<DocumentCollection>) -> ())
    func get (collectionsIn databaseId: String, maxPerPage: Int? = nil, callback: @escaping (Response<Resources<DocumentCollection>>) -> ())

    // ...
}
```

2. Then have online and offline clients implement that protocol

```swift
class OnlineClient: DocumentClient {
    // ...
}

class OfflineClient: DocumentClient {
    // ...
}
```

3. Have a static property `shared` on `DocumentClient` decide which one of the client to use depending on the network status

```swift
extension DocumentClient {
    static var shared: DocumentClient {
       return isNetworkReachable ? OnlineClient.shared : OfflineClient.shared
    }
}
```

That would allow `DocumentClient` (now `OnlineClient`) not to worry about network status and eliminate these kind of checks `guard !isOffline else { return cachedResources(at: resourceLocation, callback: callback) }`.

There would still be some amount of delegation from the `OnlineClient` to the `OfflineClient` (e.g. when it encounters errors like `NSURLErrorNotConnectedToInternet` or `NSURLErrorNetworkConnectionLost`) but overall I think it's a clean design.

Thougths? @colbylwilliams
