### ISSUE TITLE
Ensure Database deletion API coverage similar to Android

### ISSUE THREAD

**Issue by NateRickard** [Azure/Azure.iOS#31]
We support the following Database deletion methods on Android:

```
AzureData.deleteDatabase (id) {
    // successfully deleted == it.isSuccessful
}

AzureData.deleteDatabase (database) {
    // successfully deleted == it.isSuccessful
}

database.delete {
    // successfully deleted == it.isSuccessful
}
```

Need to:

- [ ] Make sure all APIs/overloads are supported in iOS library
- [ ] Add examples to the [docs](https://github.com/Azure/Azure.iOS/wiki/AzureData)

**Comment by colbylwilliams** [comment]
## Code
[`AzureData.delete(database) {}`](https://github.com/Azure/Azure.iOS/blob/master/AzureData/Source/AzureData.swift#L71-L74)
[`database.delete {}`](https://github.com/Azure/Azure.iOS/blob/master/AzureData/Source/AzureDataExtensions.swift#L15-L17)
