### ISSUE TITLE
Implement Reachability in AzureCore

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.iOS#5]
Determine best **MIT Licensed** OSS library to provide functionality exposed in AzureCore.

List suggested libraries in comments for review and final decision.

**Comment by colbylwilliams** [comment]
This looks like the best project out there:  https://github.com/ashleymills/Reachability.swift

Fairly simple, may consider writing our own.

**Comment by colbylwilliams** [comment]
removed ReachabilityManager & tests from AzureData in 979a30f7ef7f063db0cb28719b2c257b4da74ccb

Need to add it (or another implementation to AzureCore)

**Comment by ftchirou** [comment]
Would it be okay to just add Reachability.swift as a dependency to Azure.Core through Carthage? @colbylwilliams

**Comment by colbylwilliams** [comment]
@ftchirou I just [added](https://github.com/Azure/Azure.iOS/commit/19c9ae30448437926b634857d875a42e66a6b054) the one from [Alamofire](https://github.com/Alamofire/Alamofire), rather not add another dependency for a single file.

**Comment by ftchirou** [comment]
Awesome.
