### ISSUE TITLE
Hide objective-c specific types from swift consumers

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.iOS#92]
This is more of a discussion, but I'd like to explore if it's possible to hide the types created specifically for Objective-C compatibility from Swift consumers.  Developers tend to "explore" the API using code completion in the IDE and the Objective-C (`AD`) compatibility types confuse/overwhelm this...  
 
Is this possible?  If not, can we figure out a clever work-around?

**Comment by colbylwilliams** [comment]
`NS_SWIFT_UNAVAILABLE ` looks like it could do the trick... see the docs [here](https://developer.apple.com/documentation/swift/objective_c_and_c_code_customization/making_objective_c_apis_unavailable_in_swift)

**Comment by ftchirou** [comment]
Good point! Yes, seems like `NS_SWIFT_UNAVAILABLE` will do the trick.

**Comment by ftchirou** [comment]
We could use `@available(swift, obsoloted: 1.0)`.
