### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by JasonGreenAmerica** [Azure/Azure.iOS#96]
I'm using AzureData to connect to Cosmos DB. My first attempt at adding a document failed. I used create or replace method on DocumentCollection

## Bug Information
Fatal Error in -->public enum ResourceLocation line 72
case let .child(type, resource, id):                            return ResourceOracle.getAltLink(forResource: resource)! + id.path(in:"/" + type.rawValue)
### Steps to Reproduce
-->in code snippet
### Expected Behavior
-->create document
### Code snippet
func createNewEventWith(completion: @escaping (JSON, NSError?) -> Void) {
            self.collectionId = "events"
            if(AzureData.isConfigured()){
                self.collection!.createOrReplace(self) { (response) in
                    if(response.result.isSuccess){
                        completion(JSON(response.resource!), nil)
                        return
                    }
                    debugPrint(response.error as Any)
                }
            }
        }
### Screenshots
$›
![screen shot 2018-06-29 at 11 54 24 am](https://user-images.githubusercontent.com/13971059/42109667-48e3360e-7b93-11e8-87ef-f98734f9c741.png)
![screen shot 2018-06-29 at 11 57 32 am](https://user-images.githubusercontent.com/13971059/42109795-c4e4666a-7b93-11e8-92d5-600d0537381c.png)

**Comment by srhallx** [comment]
Need to pass a Document object into createOrReplace(). It appears that DocumentCollection object is being passed in above code sample instead.  Method signature is: `createOrReplace(document: T, callback: (Response<T>) -> ())`

**Comment by colbylwilliams** [comment]
Closing issue.  Please comment again here if you need further assistance and I'll reopen the issue.
